In [14]:
# a.Using NumPy create random vector of size 15 having only Integers in the range 1-20.
import numpy as np
rV = np.random.randint(low=1, high=21, size=15)
print("Original array: ", rV)

Original array:  [10 15 19  8  4  4  1 11  2  9  1 20 19  2 13]


In [15]:
# a1. Reshape the array to 3 by 5
array = rV.reshape(3,5)
print("Reshaped array: ")
print(array)

Reshaped array: 
[[10 15 19  8  4]
 [ 4  1 11  2  9]
 [ 1 20 19  2 13]]


In [16]:
# a2. Print array shape.
array_shape = array.shape
print(array_shape)

(3, 5)


In [17]:
# a3. Replace the max in each row by 0
max_indices = np.argmax(array, axis=1)
array[np.arange(array.shape[0]), max_indices] = 0
print("Modified array:")
print(array)

Modified array:
[[10 15  0  8  4]
 [ 4  1  0  2  9]
 [ 1  0 19  2 13]]


In [28]:
# Create a 2-dimensional array of size 4 x 3 (composed of 4-byte integer elements), also print the shape, type and data type
# of the array
import numpy as np
arrayInQuestion2 = np.array([[1,2,3], [2,3,4], [3,4,5], [4,5,6]], dtype= np.int32)
print("Shape of array:", arrayInQuestion2.shape)
print("Type of array:", type(arrayInQuestion2))
print("Data type of array:", arrayInQuestion2.dtype)

Shape of array: (4, 3)
Type of array: <class 'numpy.ndarray'>
Data type of array: int32


In [18]:
# b. Write a program to compute the eigenvalues and right eigenvectors of a given square array given below:
## [[ 3 -2] [ 1 0]]

arrayInQuestion2b = np.array([[3,-2], [1,0]])
eigenValues, eigenVectors = np.linalg.eig(arrayInQuestion2b)
print("Eigenvalues:")
print(eigenValues)
print("\nRight Eigenvectors:")
print(eigenVectors)

Eigenvalues:
[2. 1.]

Right Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [21]:
# c. Compute the sum of the diagonal element of a given array.
## [[0 1 2] [3 4 5]]

arrayInQuestion2c = np.array([[0,1,2], [3,4,5]])
sumOfDiagonalElement = np.trace(arrayInQuestion2c)
print("Sum of Diagonal Element:", sumOfDiagonalElement)

Sum of Diagonal Element: 4


In [24]:
# Write a NumPy program to create a new shape to an array without changing its data.
# Reshape 3x2: 
# [[1 2]       
# [3 4]
# [5 6]]

# Reshape 2x3:
# [[1 2 3]
# [4 5 6]]

arrayInQuestion2d = np.array([[1,2], [3,4], [5,6]])
reShape3By2 = arrayInQuestion2d.reshape(2,3)
print("Reshaping 3x2 to 2x3 \n", reShape3By2)

array2InQuestion2d = np.array([[1,2,3], [4,5,6]])
reShape2By3 = array2InQuestion2d.reshape(3,2)
print("Reshaping 2x3 to 3x2 \n", reShape2By3)


Reshaping 3x2 to 2x3 
 [[1 2 3]
 [4 5 6]]
Reshaping 2x3 to 3x2 
 [[1 2]
 [3 4]
 [5 6]]
